url: "https://github.com/waqasuddinkhan/MACARON-GenMed-LabEx" # the base hostname & protocol for your site
plugins:
  - jekyll-seo-tag

google:
 username: waqasuddinkhan
 card: macaron

theme: jekyll-theme-cayman
